import Link from "next/link";
import { notFound } from "next/navigation";
import { getTechnicalLibraryDocument } from "@/services/library/actions";
type Props={params:Promise<{documentId:string}>};
function youtubeEmbedUrl(value:string|null|undefined){
 if(!value)return null; try{const url=new URL(value);const host=url.hostname.toLowerCase();
 if(host==="youtu.be"||host==="www.youtu.be"){const id=url.pathname.split("/").filter(Boolean)[0];return id?`https://www.youtube.com/embed/${encodeURIComponent(id)}`:null;}
 if(host==="youtube.com"||host==="www.youtube.com"||host.endsWith(".youtube.com")){if(url.pathname==="/watch"){const id=url.searchParams.get("v");return id?`https://www.youtube.com/embed/${encodeURIComponent(id)}`:null;}const parts=url.pathname.split("/").filter(Boolean);if(parts.length>=2&&["embed","shorts","live"].includes(parts[0]))return `https://www.youtube.com/embed/${encodeURIComponent(parts[1])}`;}}catch{} return null;
}
export default async function Page({params}:Props){
 const {documentId}=await params;const doc=await getTechnicalLibraryDocument(documentId);if(!doc)notFound();const youtube=youtubeEmbedUrl(doc.external_url);const rich=doc.source_format==="docx"&&Boolean(doc.extracted_html);
 return <main className="min-h-screen bg-[#f7f6f1] text-[#153047]"><header className="bg-[#102e43] px-6 py-6 text-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4"><Link href="/" className="font-bold tracking-[0.14em] text-[#e8cc86]">LIFENERGY</Link><Link href="/biblioteca-tecnica" className="rounded-full border border-[#e5c87f]/60 px-5 py-2 text-sm font-semibold text-[#f1d994]">Voltar à Biblioteca</Link></div></header><article className="mx-auto max-w-5xl px-6 py-14"><p className="text-xs font-bold uppercase tracking-[0.26em] text-[#a17824]">Biblioteca Técnica Lifenergy</p><h1 className="mt-3 text-4xl font-semibold leading-tight text-[#102e43]">{doc.title}</h1>{doc.description?<p className="mt-5 max-w-4xl text-lg leading-8 text-slate-600">{doc.description}</p>:null}
 <section className="mt-10 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm md:p-10">{rich?<div className="text-base leading-8 text-slate-700 [&_h1]:mb-5 [&_h1]:mt-8 [&_h1]:text-3xl [&_h1]:font-bold [&_h2]:mb-4 [&_h2]:mt-8 [&_h2]:text-2xl [&_h2]:font-bold [&_h3]:mb-3 [&_h3]:mt-6 [&_h3]:text-xl [&_h3]:font-bold [&_p]:mb-4 [&_table]:my-6 [&_table]:w-full [&_td]:border [&_td]:p-2 [&_th]:border [&_th]:p-2 [&_li]:ml-6" dangerouslySetInnerHTML={{__html:doc.extracted_html}}/>:<div className="whitespace-pre-wrap text-base leading-8 text-slate-700">{doc.extracted_text}</div>}</section>
 {youtube?<section className="mt-8"><h2 className="mb-4 text-xl font-bold text-[#0F2D4A]">Conteúdo complementar em vídeo</h2><div className="aspect-video overflow-hidden rounded-2xl bg-black"><iframe src={youtube} title={`Vídeo: ${doc.title}`} className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div></section>:doc.external_url?<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold text-[#0F2D4A]">Referência complementar</h2><a href={doc.external_url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex rounded-full border border-[#0F2D4A] px-5 py-2.5 text-sm font-bold text-[#0F2D4A]">Acessar conteúdo externo</a></section>:null}</article></main>;
}
